doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    types:
      uuid: Ramsey\Uuid\Doctrine\UuidType
      uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
    mapping_types:
      uuid_binary: binary
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Model'
        prefix: 'App\Model'
        alias: App
