services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Component\Api\ModelInterface:
      tags: [ 'api.model' ]

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\Component\Api\ModelChain: ~
  App\Controller\ApiController:
    public: true
